### PR TITLE
Fixes sitemap limit for ElasticSearch 7.x

### LINKED ISSUE #599: Elastic search limited to 10.000 entries
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | Specific version or SHA of a commit
| Sulu Version | Specific version or SHA of a commit

#### Actual Behavior

When using ElasticSearch 7.x and increasing `index.max_result_window` to 20.000 there are still only 10.000 entries displayed in backend.

#### Expected Behavior

20.000 entries should be displayed.

#### Steps to Reproduce

* Use ElasticSearch 7.x
* Create 10.001 articles
* Set index.max_result_window to 20.000
```
ongr_elasticsearch:
    managers:
        default:
            index:
                settings:
                    max_result_window: 20000
        live:
            index:
                settings:
                    max_result_window: 20000
```

#### Possible Solutions

In ElasticSearch 7.x there is a new search parameter `track_total_hits`. It must just be set to true in the query.

### PR DESCRIPTION
**Pull request by hgiesenow**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #599
| Related issues/PRs | #600
| License | MIT

#### What's in this PR?

Fixes 10k limit issues for the sitemap

#### Why?

In ES 7.x, the `track_total_hits` parameter must be added to the query, to fetch all search result.

### CODE REVIEW

File: Sitemap/ArticleSitemapProvider.php [hunk 1]
```diff
@@ -172,6 +172,7 @@ private function getBulk(Repository $repository, array $webspaceKeys, int $from,
         }
 
         $search->addQuery($webspaceQuery);
+        $search->setTrackTotalHits(true);
```
Comment (wachterjohannes) [inline Sitemap/ArticleSitemapProvider.php]: @hgiesenow can you wrap that with a `method_exists` see here https://github.com/sulu/SuluArticleBundle/pull/600/files#diff-6bb92e406267424def35c1c8b3b9d0bcbc4e784b7dd15300af0dab93a7b94477R329

**Review by wachterjohannes — CHANGES_REQUESTED** [review]

File: Sitemap/ArticleSitemapProvider.php (hunk 1 above)
Comment (hgiesenow) [reply Sitemap/ArticleSitemapProvider.php]: done. Thanks for your feedback.

**Review by wachterjohannes — APPROVED** [review]
