### PR TITLE
Fixed not working sorting with ES >= 5.0

### LINKED ISSUE #244: Admin List: Sorting by title is broken
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0.6.*
| Sulu Version | *

#### Actual Behavior

In the admin interface list: The application crashes when sorting by title is activated.

### PR DESCRIPTION
**Pull request by trickreich**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #244 
| Related issues/PRs | --
| License | MIT

#### What's in this PR?

Implemented ESFieldDescriptor to add the possibility to configure the sort field.

### CODE REVIEW

File: Controller/ArticleController.php [hunk 1]
```diff
@@ -54,25 +54,44 @@ class ArticleController extends RestController implements ClassResourceInterface
     /**
      * Create field-descriptor array.
      *
-     * @return FieldDescriptor[]
+     * @return ESFieldDescriptor[]
```
Comment (wachterjohannes) [inline Controller/ArticleController.php]: no abbreviation :) `ElasticsearchFieldDescriptor`

File: Controller/ArticleController.php [hunk 2]
```diff
@@ -54,25 +54,44 @@ class ArticleController extends RestController implements ClassResourceInterface
...
+                false
+            ),
+            'authorFullName' => new ESFieldDescriptor(
+                'authorFullName',
+                'authorFullName.raw',
+                'sulu_article.author',
+                false,
+                false
+            ),
+            'created' => new ESFieldDescriptor('created', '', 'public.created', true, false, 'datetime'),
```
Comment (wachterjohannes) [inline Controller/ArticleController.php]: use `null`

File: FieldDescriptor/ESFieldDescriptor.php [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+        $type = '',
+        $width = '',
+        $minWidth = '',
+        $sortable = true,
+        $editable = false,
+        $cssClass = ''
+    ) {
+        if ('' !== $sortField) {
+            $this->sortField = $sortField;
+        } else {
```
Comment (wachterjohannes) [inline FieldDescriptor/ESFieldDescriptor.php]: no else :)
