### PR TITLE
Fixed has-next-page in article data-provider

### LINKED ISSUE #61: hasNextPage in view object is always false
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | all

#### Actual Behavior

the hasNextPage property is always false

#### Expected Behavior

to get the right value for hasNextPage from the smartcontent contenttype

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #61
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the flag `hasNextPage` in `ArticleDataProvider`

### CODE REVIEW

File: Content/ArticleDataProvider.php [hunk 1]
```diff
@@ -108,15 +109,22 @@ public function resolveDataItems(
...
         $uuids = [];
         /** @var ArticleViewDocumentInterface $document */
-        foreach ($this->getSearchResult($filters, $limit, $page, $pageSize) as $document) {
+        foreach ($queryResult as $document) {
             $uuids[] = $document->getUuid();
             $result[] = new ArticleDataItem($document->getUuid(), $document->getTitle(), $document);
         }
 
-        return new DataProviderResult($result, false, $uuids);
+        $count = $queryResult->count();
```
Comment (alexander-schranz) [inline Content/ArticleDataProvider.php]: comment why count is not equal to limit

File: Content/ArticleDataProvider.php [hunk 2]
```diff
@@ -134,18 +142,25 @@ public function resolveResourceItems(
...
+        foreach ($queryResult as $document) {
             $uuids[] = $document->getUuid();
             $result[] = new ArticleResourceItem(
                 $document,
                 $this->getResource($document->getUuid(), $document->getLocale())
             );
         }
 
-        return new DataProviderResult($result, false, $uuids);
+        $count = $queryResult->count();
```
Comment (alexander-schranz) [inline Content/ArticleDataProvider.php]: looks like duplicated why not move into an own function
