### PR TITLE
Fixed bug when an article has no creator/changer/author

### LINKED ISSUE #88: Error after changing an article without setting a Changer
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | dev-develop

#### Actual Behavior

When saving an article - after changing it via e.g. a Command without setting a changer - following error is thrown:

```
Entity with the type "" and the id "null" not found.

Request URL:http://oelz.dev/admin/api/users/null
Request Method:GET
Status Code:404 Not Found
```

#### Expected Behavior

It should not throw an error.

#### Steps to Reproduce

1. Create an article and save it
2. Update / change the article via a command *without* setting a changer
3. Open the article in the backend and save.

#### Possible Solutions

Do not try to fetch a user when the changer is null or use the creator as changer.

### PR DESCRIPTION
**Pull request by trickreich**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #88 
| Related issues/PRs | --
| License | MIT
| Documentation PR | --

#### What's in this PR?

Frontend doesn't crash when creator, changer or author is empty.

### CODE REVIEW

File: Resources/public/js/components/articles/edit/settings/main.js [hunk 1]
```diff
@@ -279,20 +279,25 @@ define([
          * @return {*}
          */
         loadUser: function(id) {
-            var deferred = $.Deferred(),
-                user = new User({id: id});
+            var deferred = $.Deferred();
 
-            user.fetch({
-                global: false,
+            if (id) {
```
Comment (wachterjohannes) [inline Resources/public/js/components/articles/edit/settings/main.js]: use early return:

```
if(!id){
    deferred.reject();

    return deferred;
}

...
```

File: Resources/public/js/components/articles/edit/settings/main.js [hunk 2]
```diff
@@ -281,25 +281,25 @@ define([
...
-                deferred.reject();
-            }
+                success: function(model) {
+                    deferred.resolve(model)
+                }.bind(this),
 
-            return deferred;
+                error: function() {
+                    deferred.reject();
+                }.bind(this)
```
Comment (wachterjohannes) [inline Resources/public/js/components/articles/edit/settings/main.js]: missing return
